# TODO: Can't get this working on a Windows Vagrant box.
---
driver:
  name: vagrant
  # vagrantfiles:
  # - Vagrantfile.rb

provisioner:
  name: chef_solo

platforms:
  - name: windows-2012r2
    driver:
      box: 'jonathanporta/windows-2012r2-standard'
      # guest: :windows
      communicator: 'winrm'
      # network:
      # - ["forwarded_port", {guest: 3389, host: 3389}]
      # - ["forwarded_port", {guest: 5985, host: 5985}]

suites:
  - name: default
    run_list:
      - recipe[rust::default]
    attributes:
