name             'rust'
maintainer       'Jonathan Porta'
maintainer_email 'jonathan@jonathanPorta.com'
license          'all_rights'
description      'Installs/Configures the game Rust'
long_description 'Installs/Configures the survival game Rust'
version          '0.0.2'

depends 'windows'
depends 'steamcmd'
depends 'openssl'
depends 'nssm'
depends 'windows_firewall'
